backend:
  name: github
  repo: soft-bee/softbee.tech
  branch: feat/93-add-main-image-article-use-netlify-cms

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: image, logo: Image, widget: image} 
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
